spring:
  application:
    name: ccsu-score-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: @config.instance.id@
  profiles:
    active: @profiles.active@       #启动的环境，运行时指定（如：mvn spring-boot:run -Pdev）