eureka:
  instance:
    ip-address: ${IP_ADDRESS:127.0.0.1}               # 本机地址，运行时注入
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
  server:
    enable-self-preservation: false                    # 关闭自我保护模式（默认为打开）
    eviction-interval-timer-in-ms: 60000               # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms 即1分钟）
  client:
    register-with-eureka: false                        # 是否注册到注册中心
    fetch-registry: false                              # 是否拉取服务注册信息
    service-url:
      defaultZone: ${REGISTE_CENTER:http://39.106.96.220:8761/eureka/,http://120.78.82.47:8761/eureka/}   # 其他对等的注册中心（以","分隔)