server:
  port: 8888
spring:
  application:
    name: @config.instance.id@
  cloud:
    config:
      server:
        git:
          uri: @config.git.uri@
  profiles:
    active: @profiles.active@
  rabbitmq:
    host: @rabbitmq.host@
    port: @rabbitmq.port@
    username: @rabbitmq.username@
    password: @rabbitmq.password@
eureka:
  instance:
    ip-address: @ip.address@
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true                      # 注册IP （缺省为主机名）
    lease-renewal-interval-in-seconds: 15      # 服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 30   # 服务失效时间（缺省为90s）
  client:
    fetch-registry: false                        # 获取服务注册信息（配置中心不需要消费其他服务，因此设为false）
    registry-fetch-interval-seconds: 30        # 获取间隔（缺省为30秒）
management:
  endpoints:
    web:
      exposure:
        include: '*'