server:
  port: 8888
spring:
  application:
    name: @config.instance.id@
  cloud:
    config:
      server:
        git:
          uri: @config.git.uri@
  profiles:
    active: @profiles.active@
management:
  endpoints:
    web:
      exposure:
        include: '*'