spring:
  rabbitmq:
    host: mq.notobject.com
    port: 5672
    username: test
    password: test
eureka:
  client:
    service-url:
      defaultZone: http://serverb2.notobject.com:8761/eureka/,http://serverb1.notobject.com:8761/eureka/